const cache = {
    getBrands: null,
    getPlaces: null,
    getOrganizations: null,
    getTeatments: null,
    getColors: null,
    getAppeals: null,
    getUsers: null,
    getClientStatuses: null,
    getTreatmentSources: null,
    getInspection: null,
    getPolicy: null,
    getOrganization: null,
    getAllOrganizations: null,
    getUserRoles: null,
    getTimeZones: null,
    getUserLocations: null,
    getDepartments: null,
    getDomage: null,
    getRepaired: null,
    getSmsTemplates: null,
    getTreatments: null,
    getBanks: null,
    getDocumentTypes: null,
    getenabledemployeers: null,
    пetTradeInDirectionTypes: null,
    getAllOrgWithDep: null,
    getTradeinDirectionTypes: null,
    getSimularCars: null,
    getDealsByVin: null,
    getSimilarDeals: null,
    getInspectionComplectation: null,
    GetInspectionComplect: null,
    getTypeCompanies: null,
    getTypesLegal: null,
    getPositions: null
}
export default cache